### ISSUE TITLE
Locale i nbsp

### ISSUE THREAD

**Issue by Inscure** [eXtreme-Fusion/eXtreme-Fusion-CMS#262]
https://github.com/eXtreme-Fusion/eXtreme-Fusion-CMS/commit/447f694079a39e293e61a1ddb11311537a22c151#commitcomment-3912636

**Comment by SebaZ** [comment]
Ciekawe

_Sent from my Samsung SM-G935F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
