### ISSUE TITLE
Usuwanie tematów, które nie mają wpisów

### ISSUE THREAD

**Issue by Inscure** [eXtreme-Fusion/eXtreme-Fusion-CMS#269]
Usunięcie ostatniego posta w temacie powinno usuwać temat.

**Comment by SebaZ** [comment]
Ciekawe


_Sent from my Samsung SM-G935F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Rafik89** [comment]
Chyba miał na myśli pierwszego posta, sprawdzenie czy do tematu nie ma innych powiązanych postów 😀
