### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by Adi2071** [eXtreme-Fusion/eXtreme-Fusion-CMS#278]
Witam

Mam dodany modół Download. Kiedy w niego chcę wejść i dodać pliki piszę "Przepraszamy, błąd serwera. Prawdopodobnie w pliku .htaccess użyto błędnej opcji. www.cba.pl"

Proszę o pomoc.

**Comment by SebaZ** [comment]
Skoro problem dotyczy serwera cba.pl to złe miejsce na zadanie tego pytania.
